//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProgress
    {
        public int IDProgress { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Chest { get; set; }
        public Nullable<decimal> Waist { get; set; }
        public Nullable<decimal> Hips { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
