//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProgress
    {
        public int progress_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> weight { get; set; }
        public string measurements { get; set; }
        public Nullable<double> strength { get; set; }
        public Nullable<double> endurance { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
