//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int IDEquipment { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> IDStatusEquip { get; set; }
    
        public virtual StatusEquipment StatusEquipment { get; set; }
    }
}
