//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exericses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exericses()
        {
            this.WorkoutExericises = new HashSet<WorkoutExericises>();
        }
    
        public int IDExercises { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> IDMuscleType { get; set; }
        public string Photo { get; set; }
    
        public virtual MuslceType MuslceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutExericises> WorkoutExericises { get; set; }
    }
}
