//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goals
    {
        public int IDGoals { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<decimal> TargetWieght { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<int> IDStatusGoals { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual StatusGoals StatusGoals { get; set; }
    }
}
