//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Trainings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group_Trainings()
        {
            this.GroupParticipants = new HashSet<GroupParticipants>();
        }
    
        public int IDGroup { get; set; }
        public Nullable<int> IDTrainer { get; set; }
        public Nullable<int> IDWorkout { get; set; }
        public Nullable<int> MaxParticipants { get; set; }
        public Nullable<int> CurrentParticipants { get; set; }
    
        public virtual Trainers Trainers { get; set; }
        public virtual Workouts Workouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupParticipants> GroupParticipants { get; set; }
    }
}
