//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupParticipants
    {
        public int IDParticipant { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public Nullable<int> IDClient { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Group_Trainings Group_Trainings { get; set; }
    }
}
