//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meals
    {
        public int meal_id { get; set; }
        public Nullable<int> diet_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual DietPlans DietPlans { get; set; }
    }
}
