//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessGetMoreFitEntities1 : DbContext
    {
        public FitnessGetMoreFitEntities1()
            : base("name=FitnessGetMoreFitEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientProgress> ClientProgress { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Exericses> Exericses { get; set; }
        public virtual DbSet<Goals> Goals { get; set; }
        public virtual DbSet<Group_Trainings> Group_Trainings { get; set; }
        public virtual DbSet<GroupParticipants> GroupParticipants { get; set; }
        public virtual DbSet<MuslceType> MuslceType { get; set; }
        public virtual DbSet<NutritionPlans> NutritionPlans { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<StatusEquipment> StatusEquipment { get; set; }
        public virtual DbSet<StatusGoals> StatusGoals { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<TypeWorkouts> TypeWorkouts { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WorkoutExericises> WorkoutExericises { get; set; }
        public virtual DbSet<Workouts> Workouts { get; set; }
    }
}
