//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessAppEntities : DbContext
    {
        public FitnessAppEntities()
            : base("name=FitnessAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<ClientProgress> ClientProgress { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DietPlans> DietPlans { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Exercises> Exercises { get; set; }
        public virtual DbSet<GroupWorkouts> GroupWorkouts { get; set; }
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<RecoveryPlans> RecoveryPlans { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<SyncData> SyncData { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<WorkoutExercises> WorkoutExercises { get; set; }
        public virtual DbSet<WorkoutPlans> WorkoutPlans { get; set; }
        public virtual DbSet<Workouts> Workouts { get; set; }
    }
}
