//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutritionPlans
    {
        public int IDPlan { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> CaloriesPerDay { get; set; }
        public Nullable<int> Proteint { get; set; }
        public Nullable<int> Carbs { get; set; }
        public Nullable<int> Fats { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
