//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> trainer_id { get; set; }
        public double amount { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
