//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryPlans
    {
        public int recovery_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public string description { get; set; }
        public string sleep_tracker { get; set; }
        public string stretching_exercises { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
