//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncData
    {
        public int sync_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> last_sync { get; set; }
    }
}
