//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutExericises
    {
        public int IDWorkoutExericses { get; set; }
        public Nullable<int> IDWorkout { get; set; }
        public Nullable<int> IDExercises { get; set; }
        public Nullable<int> Sets { get; set; }
        public Nullable<int> Reps { get; set; }
        public Nullable<decimal> WeightUsed { get; set; }
    
        public virtual Exericses Exericses { get; set; }
        public virtual Workouts Workouts { get; set; }
    }
}
