//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutExercises
    {
        public int workout_id { get; set; }
        public int exercise_id { get; set; }
        public Nullable<int> sets { get; set; }
        public Nullable<int> reps { get; set; }
    
        public virtual Exercises Exercises { get; set; }
        public virtual Workouts Workouts { get; set; }
    }
}
