//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetMoreFit.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workouts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workouts()
        {
            this.Group_Trainings = new HashSet<Group_Trainings>();
            this.WorkoutExericises = new HashSet<WorkoutExericises>();
        }
    
        public int IDWorkout { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDTrainers { get; set; }
        public Nullable<System.DateTime> DateWorkout { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> IDType { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Trainings> Group_Trainings { get; set; }
        public virtual Trainers Trainers { get; set; }
        public virtual TypeWorkouts TypeWorkouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutExericises> WorkoutExericises { get; set; }
    }
}
